name: ETF Monitor

on:
  schedule:
    - cron: '0 */1 * * *' # Alle 1 Stunden
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # --- NEUER SCHRITT: Datei aus Secret erstellen ---
      - name: Create Portfolio JSON
        run: |
          echo '${{ secrets.PORTFOLIO_JSON }}' > portfolio.json
        # Die einfachen Anführungszeichen '' sind wichtig, damit JSON-Klammern erhalten bleiben!

      - name: Run Monitor Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py